version: "3.7"
services:
  client:
    container_name: sisu-client
    restart: unless-stopped
    image: "client"
    depends_on:
      - server
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - CHOKIDAR_USEPOLLING=1
    volumes:
      - ./client:/home/node/app:rw
      - /home/node/app/node_modules
    build:
      context: ./client
      dockerfile: ./Dockerfile
      target: base
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
  server:
    container_name: sisu
    restart: unless-stopped
    user: "1000:1000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server/src:/home/node/app/src:rw
      - ./server/nodemon.json:/home/node/app/nodemon.json
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - CHOKIDAR_USEPOLLING=1
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: base
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    command: npm run dev
  db:
    container_name: sisu-db
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - MYSQL_DATABASE=${MYSQL_DB}
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASS",
        ]
      timeout: 3s
      interval: 1s
      retries: 12
